export enum entryPointEnum {
  Approve = "approve",
  Add_liquidity = "add_liquidity",
  Remove_liquidity_js_client = "remove_liquidity_js_client",
  Swap_exact_cspr_for_tokens = "swap_exact_cspr_for_tokens",
  Swap_tokens_for_exact_cspr = "swap_tokens_for_exact_cspr",
  Swap_exact_tokens_for_cspr = "swap_exact_tokens_for_cspr",
  Swap_exact_tokens_for_cspr_js_client = "swap_exact_tokens_for_cspr_js_client",
  Swap_exact_tokens_for_tokens_js_client = "swap_exact_tokens_for_tokens_js_client",
  Swap_cspr_for_exact_tokens_js_client = "swap_cspr_for_exact_tokens_js_client",
  Swap_tokens_for_exact_cspr_js_client = "swap_tokens_for_exact_cspr_js_client",
  Swap_tokens_for_exact_tokens_js_client = "swap_tokens_for_exact_tokens_js_client",
  Increase_allowance = "increase_allowance",
  Decrease_allowance = "decrease_allowance",
}
